ALTER TABLE "decisions" DROP COLUMN IF EXISTS "competitor_detected";
ALTER TABLE "decisions" ADD COLUMN "competitor_detected" TEXT;
ALTER TABLE "decisions" ADD COLUMN "segment_used" TEXT;
ALTER TABLE "decisions" ADD COLUMN "needs_review" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "decisions" ADD COLUMN "review_reason" TEXT;
ALTER TABLE "decisions" ADD COLUMN "composite_score_lower" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "decisions" ADD COLUMN "composite_score_upper" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "decisions" ADD COLUMN "mode_confidence" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "decisions" ADD COLUMN "mode_probabilities" JSONB;
CREATE INDEX IF NOT EXISTS "idx_segment_weights_sample" ON "segmented_weights" ("segment_type", "segment_key", "sample_size");
CREATE INDEX IF NOT EXISTS "idx_decisions_post_id" ON "decisions" ("post_id");
CREATE INDEX IF NOT EXISTS "idx_decisions_composite_mode_needs_review" ON "decisions" ("created_at", "composite_score", "mode", "needs_review");
CREATE INDEX IF NOT EXISTS "idx_posts_processed_at_null" ON "posts" ("processed_at") WHERE "processed_at" IS NULL;
